"""
Script to update README.md with actual coverage percentage from coverage.xml
This ensures the coverage badge is always up-to-date with the actual test coverage.

Generated by coverage.py in XML format (Cobertura format).
Extracts the line-rate attribute which represents overall coverage.
"""

import re
import sys
import xml.etree.ElementTree as ET


def get_coverage_from_xml(xml_file: str = "coverage.xml") -> float | None:
    """
    Extract coverage percentage from coverage.xml file.

    Args:
        xml_file: Path to coverage.xml file (Cobertura format)

    Returns:
        Coverage percentage as float (e.g., 97.51)
    """
    try:
        tree = ET.parse(xml_file)
        root = tree.getroot()

        # Get line-rate attribute from root element (represents overall line coverage)
        # line-rate is in decimal format (0.9751 = 97.51%)
        line_rate = root.get("line-rate")

        if line_rate:
            # Convert from decimal (0.9751) to percentage (97.51)
            coverage_percent = float(line_rate) * 100
            return round(coverage_percent, 2)
        else:
            print(f"⚠️  Could not find line-rate in {xml_file}")
            return None
    except FileNotFoundError:
        print(f"❌ {xml_file} not found. Run: pytest --cov=src --cov-report=xml")
        return None
    except ET.ParseError as e:
        print(f"❌ Error parsing {xml_file}: {e}")
        return None


def update_readme_coverage(
    coverage_percent: float, readme_file: str = "README.md"
) -> bool:
    """
    Update the coverage badge in README.md with actual coverage percentage.

    Args:
        coverage_percent: Coverage percentage as float
        readme_file: Path to README.md

    Returns:
        True if successful, False otherwise
    """
    try:
        # Read README
        with open(readme_file, "r", encoding="utf-8") as f:
            content = f.read()

        # Determine badge color based on coverage level
        if coverage_percent >= 90:
            color = "brightgreen"
        elif coverage_percent >= 80:
            color = "yellowgreen"
        elif coverage_percent >= 70:
            color = "yellow"
        elif coverage_percent >= 60:
            color = "orange"
        else:
            color = "red"

        # Create new badge with actual coverage
        coverage_rounded = round(coverage_percent, 2)
        new_badge = f"[![Code Coverage](https://img.shields.io/badge/coverage-{coverage_rounded}%25-{color}.svg)]()"

        # Replace old coverage badge (look for the coverage badge pattern)
        # Pattern matches: [![Code Coverage](...)]()
        pattern = r"\[\!?\[Code Coverage\]\(.*?\)\]\(\)"
        updated_content = re.sub(pattern, new_badge, content)

        # Check if replacement was made
        if updated_content == content:
            print(f"⚠️  Could not find coverage badge in {readme_file}")
            return False

        # Write updated README
        with open(readme_file, "w", encoding="utf-8") as f:
            f.write(updated_content)

        print(f"✅ Updated README.md with coverage: {coverage_rounded}%")
        return True

    except (IOError, OSError) as e:
        print(f"❌ Error updating README.md: {e}")
        return False


def main():
    """Main function to run coverage update."""
    print("📊 Updating coverage badge in README.md...")
    print("   Reading from: coverage.xml (Cobertura format)")

    # Get coverage from coverage.xml
    coverage = get_coverage_from_xml()

    if coverage is None:
        print("\n❌ Could not get coverage percentage. Try running tests first:")
        print("   pytest --cov=src --cov-report=xml --cov-report=html")
        return False

    print(f"📈 Found coverage: {coverage}%")

    # Determine quality level
    if coverage >= 90:
        quality = "Excellent 🌟"
    elif coverage >= 80:
        quality = "Good ✅"
    elif coverage >= 70:
        quality = "Fair ⚠️"
    else:
        quality = "Needs improvement ❌"

    print(f"   Quality: {quality}")

    # Update README
    if update_readme_coverage(coverage):
        print("✅ Coverage badge updated successfully!")
        return True
    else:
        print("❌ Failed to update coverage badge")
        return False


if __name__ == "__main__":
    SUCCESS = main()
    sys.exit(0 if SUCCESS else 1)
